### ISSUE TITLE
[BUG] Using `Alpha` with other quantities and a custom optimizer

### ISSUE THREAD

**Issue by nmndeep** [f-dangel/cockpit#5] opened 2021-06-14 11:47 UTC
## No support yet for custom optimizers?
---
 Error(log below) while trying cockpit with custom optimizer class(that subclasses torch.optim.Optimizer). Although seems to work as expected with in-built optimizers (torch.optim.SGD). 

#### Log
Traceback (most recent call last):
  File "laplace_primer.py", line 137, in <module>
    sgld.train(prefinal_train, train_loader, model)
  File "../SGLD_laplace.py", line 123, in train
    loss.backward(create_graph=cockpit.create_graph(epochs))
  File "./miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/context.py", line 137, in __exit__
    self.cp.track(self.global_step, protected_savefields=self.protected_savefields)
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/cockpit.py", line 178, in track
    q.track(global_step, self.params, batch_loss)
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/quantity.py", line 87, in track
    iteration, result = self.compute(global_step, params, batch_loss)
  File "./miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/quantity.py", line 516, in compute
    save_result = self._compute(global_step, params, batch_loss)
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/quantity.py", line 538, in _compute
    self._compute_start(global_step, params, batch_loss)
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/alpha.py", line 280, in _compute_start
    self._save_1st_order_info(global_step, params, batch_loss, point, until)
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/alpha.py", line 332, in _save_1st_order_info
    id(p): batch_size * p.grad_batch.data.clone().detach() for p in params
  File "../miniconda3/envs/backpack/lib/python3.7/site-packages/cockpit/quantities/alpha.py", line 332, in <dictcomp>
    id(p): batch_size * p.grad_batch.data.clone().detach() for p in params
AttributeError: 'Parameter' object has no attribute 'grad_batch'

**Comment by f-dangel** [comment] 2021-06-14 13:07
Hey,

thanks for your report. The error message looks like a hook that accesses individual gradients of a parameter is executed before that information is available. My first guess is that this is related to the architecture you are using, rather than the optimizer.

Do you have a small working example to reproduce the behavior?

**Comment by nmndeep** [comment] 2021-06-14 15:13
I have created a gist or the issue. Function train() in class Runner in example.py has implementation of cockpit related-module. [https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a](https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a)
Please let me know, if this doesn't work.

**Comment by f-dangel** [comment] 2021-06-14 16:24
I cannot execute the code due to missing dependencies (`SGLD_base`). I assume you want to use [this](https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a#file-example-py-L20-L29) network with [this](https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a#file-example-py-L58) optimizer.

Some questions before I start guessing solutions:
* Does the combination `Model1` + `SGD` work? If so, the problem should be related to using a custom optimizer
* Does [this line](https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a#file-example-py-L52) + `SGD` work? If so, the problem should be related to the neural network architecture.

Without being able to verify my claims, I think you could try the following: Replace `self.model = Model1(self.inp, self.n_classes)` with
```python
self.model = make_model(self.inp, self.n_classes)
```
where
```python
def make_model(inp, n_classes):
    """Create a BackPACK-compatible model."""
    linear = nn.Linear(inp, n_classes, bias=True)
    torch.nn.init.kaiming_uniform(linear.weight)

    return torch.nn.Sequential(linear)
```

**Comment by nmndeep** [comment] 2021-06-14 18:34
- I have not been using `Model1` class, even for your suggestion(3rd point) I get the same error .
- [This line](https://gist.github.com/nmndeep/5eb465524aae9cc328f6cc394ccb146a#file-example-py-L52) + `SGD` works.
- Your suggestion of 
`self.model = make_model(self.inp, self.n_classes)
` works with SGD but not with the custom optimizer. 
I have also created a gist for the optimizer class. [SGLD_base](https://gist.github.com/nmndeep/8cae4be1559e26788af7b6424c1758c4).

**Comment by f-dangel** [comment] 2021-06-16 14:58
Hi again,

I tried to run your provided example, but keep running into missing imports (`hessian`, `utils`, ...). Please simplify your example, e.g. provide a single script and the dependencies that must be installed.

**Comment by nmndeep** [comment] 2021-06-16 19:52
Hi, Sorry for the external dependencies, I have updated the files and the only external functionalities now are from standard libraries.

**Comment by f-dangel** [comment] 2021-06-23 07:08
Thank for the update. I can now execute the script and all imports succeed. But the example seems to be lacking an actual train run that leads to the error.

**Comment by fsschneider** [comment] 2021-10-25 09:47
PR #18 solved this issue and I will close this issue.

**Closed as completed by fsschneider** 2021-10-25 09:47 UTC
Labels: 🐛 Type: Bug, 👍 Status: Done
